### ISSUE TITLE
Error encountered in JUnitReport .java file

### ISSUE THREAD

**Issue by girlmerry2000** [RationaleEmotions/junitreport#1]
@KrishnanMahadevan 
If I understand, I need to clone https://github.com/RationaleEmotions/junitreport and compile as a jar, then put it on my project and add below the dependency text you mentioned to the testng.xml file.
But now, I encounter an error in JUnitReport .java and can't compile it due to no below classes. Is these 2 classes missing? Please advice, thanks in advance.
import com.rationaleemotions.junit.ObjectFactory;
import com.rationaleemotions.junit.Testsuite;

**Comment by krmahadevan** [comment]
@girlmerry2000 - No you don't. Its available as a maven dependency

Please refer to the [README.md](https://github.com/RationaleEmotions/junitreport/blob/master/README.md) file for documentation.

**Comment by krmahadevan** [comment]
Closing this issue. Please comment if you are still experiencing problems.
